import type { Metadata } from "next";
import { Afacad, Geist, Geist_Mono, Raleway, Rokkitt } from "next/font/google";
import "./globals.css";
import NavMain from "@/components/nav-main";

const afacad = Afacad({
  variable: "--font-afacad",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const rokkitt = Rokkitt({
  variable: "--font-rokkitt-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${afacad.variable} ${raleway.variable} ${rokkitt.variable}  antialiased`}
      >
        <header className="content-grid">
          <NavMain />
        </header>
        {children}
      </body>
    </html>
  );
}
